### PR TITLE
Added optional paramaters to login API

### PR DESCRIPTION
**Pull request by akiroz**
Added `parameters` to the new `/oauth/token` API since the old `/oauth/ro` API is deprecated.

### CODE REVIEW

**Comment by cocojoe** [comment]
Out of interest, what parameters are you sending?
Also to pass CI you need to fix your formatting, https://circleci.com/gh/auth0/Auth0.swift/438?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by akiroz** [comment]
@cocojoe Thanks for reviewing this, I'm passing custom params to a rule. The app I'm working on is internal and requires device whitelisting.

I've fixed the code style but I'm not sure why the tests are failing now...

**Comment by cocojoe** [comment]
Thanks, will review soon.

**Comment by cocojoe** [comment]
@akiroz looks good, please add some tests, so we know that parameters are being passed etc

**Comment by akiroz** [comment]
@cocojoe Test added!

**Comment by dylanmoo** [comment]
Would love to see this merged in! I am using the Lock library for login, but Auth0 login for our test cases.

**Comment by cocojoe** [comment]
Sorry for delay, was on Holiday.

**Pull request merged**
