### PR TITLE
Update podspec Swift version to 5.0 to match project settings

### PR DESCRIPTION
**Pull request by owainhunt**
### Changes

Change to the Swift version specified in the podspec to version 5. This matches the project settings, and will prevent the 'Conversion to Swift 5 is available' warning showing in projects using the pod.

### References

Not applicable

### Testing

Config change only, no code changes.

* [ ] This change adds unit test coverage
* [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] All existing and new tests complete without errors
* [x] All active GitHub checks have passed

### CODE REVIEW

**Comment by cocojoe** [comment]
I had presumed this was setting the `minimum` version and that it would match the developers project settings as the Library supports 4.x/5.x. 

However, looks like the *fix* for this that covers all developers is:
http://blog.cocoapods.org/CocoaPods-1.7.0-beta/#support-for-multiple-swift-versions

**Comment by cocojoe** [comment]
@owainhunt as 1.7.x is GA, please can you amend your PR to use the recommended guidance as per last comment. Thanks

**Comment by owainhunt** [comment]
Change made as requested.

**Comment by cocojoe** [comment]
Looks good 👍 Have you tested it?

**Comment by owainhunt** [comment]
Indeed, tested with Swift 4.2 and 5.

**Pull request merged**
