### PR TITLE
Adds ability to injects additional headers to token end points.

### PR DESCRIPTION
**Pull request by shankarphadatare2**
### Changes

Adds ability to injects additional headers to token end points and also add existing headers to newly created URLSession instance.

### References

Please include relevant links supporting this change such as a:

- support ticket : https://support.auth0.com/tickets/00494150

Please note any links that are not publicly accessible.

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

* [ ] This change adds unit test coverage
* [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

* [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ ] All existing and new tests complete without errors
* [ ] All active GitHub checks have passed

### CODE REVIEW

**Comment by Widcket** [comment]
Hi @shankarphadatare2, thanks for raising this.

The changes to pass custom headers to the `renew` method of the Authentication API client are not necessary. The API clients allow passing a custom URL session: https://github.com/auth0/Auth0.swift/blob/master/Auth0/Auth0.swift#L38

For that same reason, the changes to Credentials Manager are no necessary either, since the Credentials Manager accepts an Authentication API client instance via the initializer: https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift#L46

So, the only thing that is needed is to add a way to pass a custom URL session when doing web auth. Like, a session property in the initializer, that is analogous to the Authentication API client: https://github.com/auth0/Auth0.swift/blob/master/Auth0/WebAuthenticatable.swift

If you want to implement that, we'll accept it as long as it has sufficient tests. But we cannot accept this PR as-is.

**Comment by shankarphadatare2** [comment]
Hi @Widcket, Yeah i agree with you, Can you implement to pass custom URLSession when doing web auth? this way we can pass our URLsession with headers.
Thanks,
Shankar

**Comment by Widcket** [comment]
@shankarphadatare2 we don't plan on doing this before the new major, so if you'd prefer to have it sooner we'll be happy to accept a PR as described.

**Comment by shankarphadatare2** [comment]
@Widcket  i prefer to have it sooner so we can just switch to your repo release version.

**Comment by Widcket** [comment]
I'll be closing this PR then, since the changes for the described implementation are completely different.

**Comment by shankarphadatare2** [comment]
@Widcket just want to check, Is this enhancement implemented and released?

**Comment by Widcket** [comment]
Hi @shankarphadatare2, we're currently working on a new major version of the library, and we'll be adding a way to add custom headers.

**Comment by Widcket** [comment]
@shankarphadatare2 Auth0.swift [2.0.0-beta.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0-beta.0) is out now, and it includes the ability to specify custom headers. See https://github.com/auth0/Auth0.swift/issues/637 for more information.

**Comment by Widcket** [comment]
The [2.0.0](https://github.com/auth0/Auth0.swift/releases/tag/2.0.0) release is out now. Please check the [Migration Guide](https://github.com/auth0/Auth0.swift/blob/master/V2_MIGRATION_GUIDE.md) for more information on how to update your apps.

**Pull request closed without merging**
