### PR TITLE
Implement Encodable/Decodable protocol in UserInfo

### PR DESCRIPTION
**Pull request by eaceto**
### Changes

Please describe both what is changing and why this is important. Include:

- Implement Encodable and Decodable protocols in UserInfo class.

### References

Please include relevant links supporting this change such as a:

- This functionality came out of a conversation with Joey deVilla and Dan Arias, for a blog post by Auth0 Guest Authors, in the Auth0 Guest Author's Slack.

### Testing

Test 

* [X] This change adds unit test coverage.
* [X] This change has been tested on the latest version of the platform/language.

### Checklist

* [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [X] All existing and new tests complete without errors
* [X] All active GitHub checks have passed

### CODE REVIEW

**Comment by Widcket** [comment]
Hi @eaceto, thank you for raising this.

Please add tests that cover all the new code.

**Comment by eaceto** [comment]
Hello @Widcket 

I did implemented the same tests that already exist for UserInfo but using Codable. I will take a look if there is any edge case missing and add it.

Thanks

**Comment by eaceto** [comment]
Morning @Widcket  and team! I have added tests on some protocols and other cases for UserInfo+Codable.
Please, feel free to review it and send me any feedback or comment you may have.
Regards,
Kimi.-

**Comment by Widcket** [comment]
> This functionality came out of a conversation with Joey deVilla and Dan Arias, for a blog post by Auth0 Guest Authors, in the Auth0 Guest Author's Slack.

@eaceto could you please expand on this conversation, and why UserInfo should implement Codable?

**Comment by eaceto** [comment]
Hello @Widcket

The possibility that UserInfo implements the Codable (Encodable & Decodable) protocol allows SDK users to serialise / deserialise instances of UserInfo in order to, send them over a network connection, saving UserInfo data to disk and loading it later.

From the user perspective, a user case of this feature may be in an Offline First application, where the user enters the app and could not retrieve an updated UserInfo from network, but yes the latest downloaded version stored in UserDefaults, for example.

As I see the main benefit of implementing this feature in the SDK is that code is cleaner (from the SDK user perspective), and I instance of UserInfo can be easily retrieved without saving a custom/manual-object or JSON serialisation string.

From the SDK internal point of view, this will allow the SDK to receive a UserInfo from a network connection using the Codable Protocol instead of the current implementation (https://github.com/auth0/Auth0.swift/blob/408a9bfcbe3deee6c17c36d66e9c6bd16ab1d4c6/Auth0/Handlers.swift#L38)

**Comment by eaceto** [comment]
Hello @Widcket . Do you need any additional information that I did not provide yet? 
Let me know about it.
Thanks, have a nice week.

**Pull request closed without merging**
